### ISSUE TITLE
Replace ring by rust-argon2, rand, hmac and sha2

### ISSUE THREAD

**Issue by thespooler** [HeroicKatora/oxide-auth#83]
# Feature

As discussed in issue #55 and #71, it seems that moving away from ring is the most sensible way to integrate with other projects that might have conflicting package version requirements.

## Alternatives

Leave ring, split crates, try to follow other projects dependencies and match ring versions accordingly.

## Context

actix-web 2.0 when used with actix-identity or actix-session requires ring 0.16.9, while oxide-auth requires ring < 0.15.

## Tracking pull request

 - [x] Replace pbkdf2 by Argon2 in registrar #86
 - [x] Replace ring in generator #85
 - [x] Replace ring in registrar #86 
 - [x] Replace ring in pkce code_grant extension #85
 - [x] Remove ring from dependencies and tests #87 

### Related 
 - [ ] Update to actix-web 2.0 #71
 - [ ] Ring question #55
 - [ ] Ring 0.16 actix web 2.0 #73
